color:
  brandColors:
    - '#B8ECD7'
    - '#083643'
    - '#B1E001'
    - '#CEF09D'
    - '#476C5E'
  brandStrength: 0.544764
  lightness: 0.376689
  rhythmicContrast: 0.327703
  saturation: 0.670344
layout_spectrum: 0.858953
name: 'ATeam Singapore '
typography_spectrum: 0.381757
